# Generated by Django 3.1.7 on 2021-02-28 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=250)),
                ('album', models.CharField(max_length=250)),
                ('length', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=100)),
                ('sub_genre', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('instruments', models.CharField(max_length=250)),
                ('similar_bands', models.CharField(max_length=250)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.artist')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.band')),
            ],
        ),
    ]
